<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

		<ItemGroup>
				<PackageReference Include="BepInEx.Analyzers" Version="1.0.8">
						<PrivateAssets>all</PrivateAssets>
				</PackageReference>
				<PackageReference Include="BepInEx.Core" Version="5.4.21" />
				<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
				<PackageReference Include="UnityEngine.Modules" Version="6000.0.77">
						<PrivateAssets>all</PrivateAssets>
						<IncludeAssets>all</IncludeAssets>
				</PackageReference>
		</ItemGroup>

		<ItemGroup>
		  <ProjectReference Include="..\Lavender\Lavender.csproj" />
		</ItemGroup>

		<ItemGroup>
				<Reference Include="$(DependsDir)/Assembly-CSharp.dll" Publicize="true" />
				<Reference Include="$(DependsDir)/Assembly-CSharp-firstpass.dll" Publicize="true" />
				<Reference Include="$(DependsDir)/UnityEngine.UI.dll" Publicize="true" />
				<Reference Include="$(DependsDir)/Unity.TextMeshPro.dll" Publicize="true" />
		</ItemGroup>

		<Import Project="$(SolutionDir)Config.Build.user.props" />

</Project>
